name: Build

on:
  push:
    branches:
      - FG_1.2
      - FG_1.2-*
  pull_request:
    branches:
      - FG_1.2
      - FG_1.2-*
  workflow_dispatch: {}

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}-gradle
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Build with Gradle
      env: 
        CHECK_JDK_COMPATIBILITY: true
      run: ./gradlew build
    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test results
        path: build/test-results/test
