name: Publisher(SNAPSHOTs)
"on":
  - workflow_dispatch
jobs:
  build:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.ACTIONS_PAT }}"
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: anatawa12/something-releaser@v2

      - run: set-git-user anatawa12-bot

      - name: Update Version
        id: up
        run: |
          # check current version
          VERSION="$(get-version)"
          if ! [[ "$VERSION" = *-SNAPSHOT ]]; then
            echo 'VERSION IS NOT SNAPSHOT' >&2
            exit 1
          fi

      - name: Prepare Build
        run: |
          prepare-gradle-signing "$GPG_PRIVATE_KEY" "$GPG_PRIVATE_PASS"
          prepare-gradle-maven "https://oss.sonatype.org/content/repositories/snapshots" \
            --user "$SONATYPE_USER" \
            --pass "$SONATYPE_PASS"
        env:
          GPG_PRIVATE_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
          GPG_PRIVATE_PASS: "${{ secrets.GPG_PRIVATE_PASS }}"
          SONATYPE_USER: "${{ secrets.SONATYPE_USER }}"
          SONATYPE_PASS: "${{ secrets.SONATYPE_PASS }}"

      - run: |
          ./gradlew publish
